# Generated by Django 3.0.6 on 2020-05-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200526_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=False, max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('eventid', models.CharField(default=False, max_length=30)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='aboutevents',
            name='eventid',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
