# Generated by Django 3.0.6 on 2020-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200601_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamreg',
            name='squadlogo',
            field=models.CharField(max_length=30, null=True, verbose_name=''),
        ),
    ]
